[build]
  command = "node build.js"
  publish = "."

# SPA fallback — all routes serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# But not for actual files
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200

[[redirects]]
  from = "/fonts/*"
  to = "/fonts/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
